name: Publish to Package Registries

on: 
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    name: Build Package
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@main
      with:
        dotnet-version: '3.1'
    - name: Build with dotnet
      run: dotnet build MtconnectCore --configuration Release
      
    - name: Pack
      run: dotnet pack MtconnectCore --configuration Release -o finalpackage --no-build
    
    - name: Publish Artifact
      uses: actions/upload-artifact@main
      with:
        name: nupkg
        path: finalpackage

  deploy:
    needs: build
    name: Deploy Packages
    runs-on: windows-latest
    
    steps:
      - name: Setup .NET Core
        uses: actions/setup-dotnet@main
        with:
          dotnet-version: '3.1'

      - name: Download Artifact
        uses: actions/download-artifact@main
        with:
          name: nupkg
      
      - name: Setup NuGet
        uses: NuGet/setup-nuget@main
        with:
          nuget-api-key: ${{ secrets.NUGETORG_API_KEY }}
          nuget-version: latest
          
      - name: Push to NuGet
        run: dotnet nuget push nupkg\*.nupkg -k ${{ secrets.NUGETORG_API_KEY }} -s https://nuget.org --skip-duplicate
