# This action checks the latest Release from the mtconnect/mtconnect_sysml_model repository, then triggers the transpiler action
name: Check SysML Release

on:
  schedule:
    - cron: '0 0 * * *' # run every day at midnight UTC
  workflow_dispatch:

jobs:
  check-latest-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install version-parser
      run: pip install version-parser
    - name: Get MTConnectCore release tag
      id: get-core-release
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        repository: TrueAnalyticsSolutions/MtconnectCore
    - name: Get MTConnect release tag
      id: get-mtc-release
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        repository: mtconnect/mtconnect_sysml_model
    - uses: jannekem/run-python-script-action@v1
      id: script
      with:
        fail-on-error: false
        script: |
          from version_parser import Version
          this_version = Version("${{ steps.get-core-release.outputs.release }}")
          mtc_version = Version("${{ steps.get-mtc-release.outputs.release }}")
          if mtc_version > this_version:
            print(1)
          else:
            print(0)
    - name: Compare Versions
      if: ${{ steps.script.stdout == '1' }}
      run: echo "MTConnect has been updated, therefore the Transpiler should be run to updated MtconnectCore."
      env:
        VERSION_DIFF: steps.script.stdout
    - name: GitHub Compare
      id: comparison
      uses: actions/github-script@v5
      with:
        script: |
            const thisVersion = "${{ steps.get-core-release.outputs.release }}";
            const mtcVersion = "${{ steps.get-mtc-release.outputs.release }}";
            console.log(`MtconnectCore Version: ${thisVersion}`);
            console.log(`MTConnect Version: ${mtcVersion}`);
            if (${{ steps.script.stdout }} > 0) {
              console.log('MTConnect has been updated, therefore the Transpiler should be run to updated MtconnectCore.');
            } else {
              console.log('MtconnectCore has the latest MTConnect updates.');
            }
