# This action checks the latest Release from the mtconnect/mtconnect_sysml_model repository, then triggers the transpiler action
name: Check SysML Release

on:
  schedule:
    - cron: '0 0 * * *' # run every day at midnight UTC
  workflow_dispatch:

jobs:
  check-latest-release:
    runs-on: ubuntu-latest
    steps:
    - name: Install SemVer
      run: pip install semver
    - name: Get MTConnectCore release tag
      id: get-core-release
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        repository: TrueAnalyticsSolutions/MtconnectCore
    - name: Get MTConnect release tag
      id: get-mtc-release
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        repository: mtconnect/mtconnect_sysml_model
    - name: Compare Versions
      id: comparison
      uses: actions/github-script@v5
      with:
        script: |
            const thisVersion = "${{ steps.get-core-release.outputs.release }}";
            const mtcVersion = "${{ steps.get-mtc-release.outputs.release }}";
            console.log(`MtconnectCore Version: ${thisVersion}`);
            console.log(`MTConnect Version: ${mtcVersion}`);
            if (semver.compare(mtcVersion, thisVersion) > 0) {
              console.log('MTConnect has been updated, therefore the Transpiler should be run to updated MtconnectCore.');
            } else {
              console.log('MtconnectCore has the latest MTConnect updates.');
            }
