# This action checks the latest Release from the mtconnect/mtconnect_sysml_model repository, then triggers the transpiler action
name: Check SysML Release

on:
  schedule:
    - cron: '0 0 * * *' # run every day at midnight UTC
  workflow_dispatch:

jobs:
  check-latest-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout mtconnect_sysml_model repository
      uses: actions/checkout@v2
      with:
        repository: mtconnect/mtconnect_sysml_model
        ref: master

    - name: Get MTConnect release tag
      id: get-mtc-release
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const res = await github.repos.getLatestRelease({
            owner: 'mtconnect',
            repo: 'mtconnect_sysml_model'
          });
          console.log(res.data.tag_name);
          console.log(res.data.zipball_url);
          console.log(res.data.published_at);
          console.log(res.data.body);
          return {
            tag_name: res.data.tag_name,
            published_at: res.data.published_at
          }
    - name: Compare Versions
      id: comparison
      uses: actions/github-script@v5
      with:
        script: |
            const semver = require('semver');
            const thisVersion = "${{ github.event.release.tag_name }}";
            const mtcVersion = "${{ steps.get-latest-release.outputs.tag_name }}";
            console.log(`MtconnectCore Version: ${thisVersion}`);
            console.log(`MTConnect Version: ${mtcVersion}`);
            if (semver.gt(mtcVersion, thisVersion)) {
              console.log('MTConnect has been updated, therefore the Transpiler should be run to updated MtconnectCore.');
            } else {
              console.log('MtconnectCore has the latest MTConnect updates.');
            }
