# This action checks the latest Release from the mtconnect/mtconnect_sysml_model repository, then triggers the transpiler action
name: Check SysML Release

on:
  schedule:
    - cron: '0 0 * * *' # run every day at midnight UTC
  workflow_dispatch:

jobs:
  check-latest-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install version-parser
      run: pip install version-parser
    - name: Get MTConnectCore release tag
      id: get-core-release
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        repository: TrueAnalyticsSolutions/MtconnectCore
    - name: Get MTConnect release tag
      id: get-mtc-release
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        repository: mtconnect/mtconnect_sysml_model
    - uses: jannekem/run-python-script-action@v1
      id: script
      with:
        fail-on-error: false
        script: |
          from version_parser import Version
          
          this_version = "${{ steps.get-core-release.outputs.release }}"[1:]
          last_dot_index = this_version.rfind('.')
          if last_dot_index != -1:
            this_version = this_version[:last_dot_index]
          
          mtc_version = "${{ steps.get-mtc-release.outputs.release }}.0"[1:]
          if Version(mtc_version) > Version(this_version):
            print(1)
          else:
            print(0)
    - name: Exit with Success
      if: steps.script.outputs.stdout > 0
      run: |
        echo "MTConnect has been updated, therefore the Transpiler should be run to updated MtconnectCore."
        exit 0
    - name: Exit with failure
      if: steps.script.outputs.stdout != 1
      run: |
        echo "MtconnectCore has the latest MTConnect updates."
        exit -1
        
